services:
  - type: web
    name: food-recommender-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b 0.0.0.0:$PORT backend.app:app
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
